import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { api, getApiErrorMessage, type ContestAnalytics as Analytics, type ContestAnalyticsParticipant } from "@/lib/api";
import { Card } from "@/components/ui/card";

const pct = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;
const number = (value: number | null) => value == null ? "—" : Number.isInteger(value) ? String(value) : value.toFixed(1);

export default function ContestAnalytics() {
  const { id } = useParams<{ id: string }>(); const contestId = Number(id);
  const [analyticsData, setData] = useState<Analytics | null>(null); const [rows, setRows] = useState<ContestAnalyticsParticipant[]>([]);
  const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [query, setQuery] = useState(""); const [queryInput, setQueryInput] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [refresh, setRefresh] = useState(0); const sequence = useRef(0);
  useEffect(()=>{const timer=window.setTimeout(()=>{setPage(1);setQuery(queryInput);},300);return()=>window.clearTimeout(timer);},[queryInput]);
  useEffect(() => { let live=true; const controller=new AbortController(); const load=async()=>{const token=++sequence.current;setLoading(true);try{const [overview, participants]=await Promise.all([api.getContestAnalytics(contestId,controller.signal),api.getContestAnalyticsParticipants(contestId,{page,pageSize:20,query},controller.signal)]);if(live&&token===sequence.current){setData(overview.analytics);setRows(participants.participants.participants);setTotal(participants.participants.total);setError("");}}catch(reason){if(live&&token===sequence.current&&!(reason instanceof DOMException&&reason.name==="AbortError"))setError(getApiErrorMessage(reason,"数据分析加载失败"));}finally{if(live&&token===sequence.current)setLoading(false);}};load();return()=>{live=false;controller.abort();};},[contestId,page,query,refresh]);
  useEffect(()=>{if(analyticsData?.contestId!==contestId||analyticsData.phase!=="RUNNING")return;const timer=window.setInterval(()=>setRefresh(value=>value+1),15000);return()=>window.clearInterval(timer);},[contestId,analyticsData?.contestId,analyticsData?.phase]);
  const visibleData=analyticsData?.contestId===contestId?analyticsData:null;
  if(loading&&!visibleData)return <div className="py-20 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-zinc-400"/></div>;
  if(!visibleData)return <div className="mx-auto max-w-7xl p-6"><p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error||"数据分析不可用"}</p></div>;
  const data=visibleData; const o=data.overview;const pages=Math.max(1,Math.ceil(total/20));
  const cards: Array<[string, string | number]> = [["参赛人数",o.participantCount],["实际参与",o.activeParticipantCount],["未提交",o.inactiveParticipantCount],["总提交",o.totalSubmissionCount]];
  if(data.scoringMode === "SCORE")cards.push(["平均总分",number(o.averageTotalScore)],["最高分",number(o.maxTotalScore)],["满分人数",number(o.fullScoreParticipantCount)]);else cards.push(["平均解题",number(o.averageSolved)],["最高解题",number(o.maxSolved)],["已解者平均罚时",number(o.averagePenaltyAmongSolvedParticipants)]);
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><Link className="text-sm text-zinc-500 hover:underline" to={`/admin/contests/${contestId}`}>← 返回比赛管理</Link><div className="mt-3 mb-5"><h1 className="text-2xl font-bold">比赛数据分析</h1><p className="mt-1 text-sm text-zinc-500">{data.phase==="RUNNING"?"比赛进行中 · 数据每 15 秒更新":"数据更新于 "}{new Date(data.generatedAt).toLocaleString()}</p></div>{error&&<p role="alert" className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><Card key={label} className="min-w-0 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></Card>)}</section>
    <section className="mt-6"><h2 className="mb-3 text-lg font-semibold">题目分析</h2><Card className="overflow-x-auto p-0"><table className="min-w-[760px] text-sm"><thead className="bg-zinc-50 text-left text-zinc-600"><tr><th className="px-4 py-3">题目</th><th className="px-4 py-3">类型</th><th className="px-4 py-3">提交</th><th className="px-4 py-3">参与率</th><th className="px-4 py-3">完成人数</th><th className="px-4 py-3">完成率</th><th className="px-4 py-3">专属指标</th></tr></thead><tbody>{data.problems.map(p=><tr key={p.contestProblemId} className="border-t"><td className="max-w-64 truncate px-4 py-3" title={p.title}>{p.label} · {p.title}</td><td className="px-4 py-3">{p.problemType}</td><td className="px-4 py-3">{p.submissionCount} / {p.uniqueSubmitterCount} 人</td><td className="px-4 py-3">{pct(p.participationRate)}</td><td className="px-4 py-3">{p.successParticipantCount}</td><td className="px-4 py-3">{pct(p.successRate)}</td><td className="px-4 py-3">{p.problemType==="ALGORITHM"?`AC 率 ${pct(p.submissionAcceptanceRate)} · 平台失败 ${p.infrastructureFailureCount}`:p.problemType==="OFFICE_CHOICE"?`正确率 ${pct(p.correctSubmissionRate)}`:`最佳均分 ${number(p.averageBestScore)} · 中位 ${number(p.medianBestScore)} · 满分 ${p.perfectScoreParticipantCount??0}`}</td></tr>)}</tbody></table></Card>{data.problems.length===0&&<p className="mt-3 text-sm text-zinc-500">暂无题目数据。</p>}</section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="min-w-0 p-5"><h2 className="font-semibold">提交趋势</h2><div className="mt-4 flex h-36 items-end gap-1">{data.timeline.map((b,i)=><div key={i} className="min-w-0 flex-1" title={`${b.submissionCount} 次提交`}><div className="rounded-t bg-blue-500" style={{height:`${Math.max(3,Math.round((b.submissionCount/Math.max(1,...data.timeline.map(x=>x.submissionCount)))*100))}%`}}/><span className="mt-1 block truncate text-center text-[10px] text-zinc-500">{i+1}</span></div>)}</div>{data.timeline.length===0&&<p className="mt-3 text-sm text-zinc-500">暂无时间段数据。</p>}</Card><Card className="min-w-0 p-5"><h2 className="font-semibold">{data.scoringMode==="SCORE"?"成绩分布":"解题数分布"}</h2><div className="mt-3 space-y-2">{data.distribution.map(b=><div key={b.label} className="flex min-w-0 items-center gap-3"><span className="w-16 shrink-0 text-xs text-zinc-500">{b.label}</span><div className="h-2 min-w-0 flex-1 rounded bg-zinc-100"><div className="h-2 rounded bg-emerald-500" style={{width:`${o.participantCount?b.participantCount/o.participantCount*100:0}%`}}/></div><span className="w-8 text-right text-sm">{b.participantCount}</span></div>)}</div></Card></section>
    <section className="mt-6"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><h2 className="text-lg font-semibold">参赛者分析（{total}）</h2><label className="text-sm">搜索用户名<input className="ml-2 h-9 max-w-full rounded border px-2" value={queryInput} onChange={e=>setQueryInput(e.target.value)} /></label></div><Card className="overflow-x-auto p-0"><table className="min-w-[760px] text-sm"><thead className="bg-zinc-50 text-left text-zinc-600"><tr><th className="px-4 py-3">排名</th><th className="px-4 py-3">学生</th><th className="px-4 py-3">提交</th><th className="px-4 py-3">已提交题</th><th className="px-4 py-3">完成题</th><th className="px-4 py-3">最后活动</th><th className="px-4 py-3">{data.scoringMode==="SCORE"?"总分":"解题 / 罚时"}</th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.userId}><td className="px-4 py-3">{row.rank??"—"}</td><td className="max-w-48 truncate px-4 py-3" title={row.username}>{row.username}</td><td className="px-4 py-3">{row.totalSubmissionCount}</td><td className="px-4 py-3">{row.submittedProblemCount}</td><td className="px-4 py-3">{row.successfulProblemCount}</td><td className="px-4 py-3">{row.lastSubmissionAt?new Date(row.lastSubmissionAt).toLocaleString():"—"}</td><td className="px-4 py-3">{data.scoringMode==="SCORE"?row.totalScore:`${row.solved} / ${row.penaltyMinutes}`}</td></tr>)}</tbody></table></Card><div className="mt-3 flex items-center justify-end gap-3 text-sm"><button className="rounded border px-3 py-1 disabled:opacity-50" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><span>{page} / {pages}</span><button className="rounded border px-3 py-1 disabled:opacity-50" disabled={page===pages} onClick={()=>setPage(page+1)}>下一页</button></div></section>
  </main>;
}
